# Generated by Django 4.2.2 on 2023-06-10 11:57

import administration.models
import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', administration.models.NameField(max_length=200, unique=True)),
                ('slug', administration.models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('cover_image', administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo)),
                ('is_red_book', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', administration.models.NameField(max_length=200, unique=True)),
                ('slug', administration.models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', administration.models.NameField(max_length=200, unique=True)),
                ('slug', administration.models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='bats.family')),
            ],
            options={
                'verbose_name_plural': 'Genus',
            },
        ),
        migrations.CreateModel(
            name='BatRedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', administration.models.LanguageField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='az', max_length=2)),
                ('description', administration.models.RichTextEditorField(blank=True, null=True)),
                ('bat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bat_red_book', to='bats.bat')),
            ],
        ),
        migrations.CreateModel(
            name='BatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo)),
                ('bat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bat_images', to='bats.bat')),
            ],
        ),
        migrations.CreateModel(
            name='BatAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', administration.models.RichTextEditorField(blank=True, null=True)),
                ('habitat', administration.models.RichTextEditorField(blank=True, null=True)),
                ('threats', administration.models.RichTextEditorField(blank=True, null=True)),
                ('distribution', administration.models.RichTextEditorField(blank=True, null=True)),
                ('conservation', administration.models.RichTextEditorField(blank=True, null=True)),
                ('biology', administration.models.RichTextEditorField(blank=True, null=True)),
                ('language', administration.models.LanguageField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='az', max_length=2)),
                ('bat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bat_attributes', to='bats.bat')),
            ],
        ),
        migrations.AddField(
            model_name='bat',
            name='genus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genus', to='bats.genus'),
        ),
    ]
