# Generated by Django 4.2.2 on 2023-06-10 14:53

import administration.models
import core.helpers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0002_alter_bat_cover_image_alter_batimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bat',
            name='cover_image',
            field=administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo),
        ),
        migrations.AlterField(
            model_name='batimage',
            name='image',
            field=administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo),
        ),
    ]
