# Generated by Django 4.2.2 on 2023-06-10 12:14

import administration.models
import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetext',
            name='banner',
        ),
        migrations.AddField(
            model_name='sitetext',
            name='banner_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='banner_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='cover_image',
            field=administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo),
        ),
    ]
