# Generated by Django 4.2.2 on 2023-06-10 14:53

import administration.models
import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_sitetext_banner_sitetext_banner_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='site_info_promo_image',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='site_visit_promo',
            field=models.ImageField(blank=True, default='site/site_visit_promo.jpg', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='cover_image',
            field=administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo),
        ),
    ]
