# Generated by Django 4.2.2 on 2023-06-10 14:54

import administration.models
import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_siteinfo_site_info_promo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='site_visit_promo',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='site_visit_promo_image',
            field=models.ImageField(blank=True, default='site/site_visit_promo_image.jpg', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='cover_image',
            field=administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo),
        ),
    ]
