# Generated by Django 4.2.2 on 2023-06-10 20:20

import administration.models
import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_siteinfo_site_visit_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='about_promo_image',
            field=models.ImageField(blank=True, default='site/about_promo.jpg', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='cover_image',
            field=administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo),
        ),
    ]
