# Generated by Django 4.2.2 on 2023-06-10 20:26

import administration.models
import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_siteinfo_about_promo_image_alter_author_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='privacy_policy_promo_image',
            field=models.ImageField(blank=True, default='site/privacy_policy_promo_image.jpg', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='cover_image',
            field=administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='about_promo_image',
            field=models.ImageField(blank=True, default='site/about_promo_image.jpg', null=True, upload_to='site/'),
        ),
    ]
