# Generated by Django 4.2.2 on 2023-06-10 20:52

import administration.models
import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_siteinfo_privacy_policy_promo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='map_image',
            field=models.ImageField(blank=True, default='site/map.jpg', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='cover_image',
            field=administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='about_promo_image',
            field=models.ImageField(blank=True, default='site/about_promo.jpg', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='article_promo_image',
            field=models.ImageField(blank=True, default='site/article_promo.jpg', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='bat_promo_image',
            field=models.ImageField(blank=True, default='site/bat_promo.jpg', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='privacy_policy_promo_image',
            field=models.ImageField(blank=True, default='site/privacy_policy_promo.jpg', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='project_promo_image',
            field=models.ImageField(blank=True, default='site/project_promo.jpg', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_visit_promo_image',
            field=models.ImageField(blank=True, default='site/site_visit_promo.jpg', null=True, upload_to='site/'),
        ),
    ]
