# Generated by Django 4.2.2 on 2023-06-10 21:09

import administration.models
import core.helpers
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_siteinfo_map_image_alter_author_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='cover_image',
            field=administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo),
        ),
    ]
