# Generated by Django 4.2.2 on 2023-06-10 11:57

import administration.models
import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', administration.models.NameField(max_length=200)),
                ('slug', administration.models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('cover_image', administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo)),
                ('description', administration.models.RichTextEditorField(blank=True, null=True)),
                ('language', administration.models.LanguageField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='az', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', administration.models.NameField(max_length=200)),
                ('slug', administration.models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('cover_image', administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo)),
                ('description', administration.models.RichTextEditorField(blank=True, null=True)),
                ('results', administration.models.RichTextEditorField(blank=True, null=True)),
                ('language', administration.models.LanguageField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='az', max_length=2)),
            ],
            options={
                'verbose_name': 'Site Visit',
                'verbose_name_plural': 'Site Visits',
            },
        ),
        migrations.CreateModel(
            name='SiteVisitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo)),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visit_images', to='activities.sitevisit')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='activities.project')),
            ],
        ),
    ]
