# Generated by Django 4.2.2 on 2023-06-10 12:14

import administration.models
import core.helpers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='cover_image',
            field=administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo),
        ),
        migrations.AlterField(
            model_name='sitevisitimage',
            name='image',
            field=administration.models.ImageField(upload_to=core.helpers.UploadImageStrategy.uploadTo),
        ),
    ]
